name: Pre Merge Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  gradle:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
      GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@a8f75513eafdebd8141bd1cd4e30fcd194af8dfa # v2.12.0
        with:
          dependency-graph: generate-and-submit
      - name: Run Gradle tasks
        run: ./gradlew :measure-builds:preMerge --continue
      - name: Stop Gradle
        run: ./gradlew --stop
